### ISSUE TITLE
Podcasts blocked (||tritondigital.com^)

### ISSUE THREAD

**Issue by THEtomaso** [wolfbeast/lunarblocklist#3]
### Issue:
Podcasts are blocked on various sites.

### Example:
https://podcasts.google.com/?q=conan%20o%27brien/

### Screenshot:
Not needed, as the problem is obvious.

### Problem rule:
`||tritondigital.com^`

### Elaboration:
**AdGuard Tracking Protection** filter and **EasyPrivacy** both have more specific rules in place.

* **AdGuard Tracking Protection filter**:
`||lt*.tritondigital.com^`

* **EasyPrivacy**:
```
||lt.tritondigital.com^
||tritondigital.com/lt?sid*&hasads=
||tritondigital.com/ltflash.php?
||tritondigital.com/ltjs.php
```

### Related issue:
https://github.com/wolfbeast/lunarblocklist/issues/1/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by wolfbeast** [comment]
It does seem that all media is served from *.mc.tritondigital.com (mc=mediaclip?) so that could be excepted regardless of domain.

**Comment by THEtomaso** [comment]
Yeah, whitelisting only **mc.tritondigital.com** allows the podcasts to play.
At least at both of those example sites which I've stumbled on so far (**podcasts.google.com** and **omny.fm**)!
