### ISSUE TITLE
.com/ad/ - Issues at multiple sites

### ISSUE THREAD

**Issue by THEtomaso** [wolfbeast/lunarblocklist#5]
### Issue:
Known problem rule causes issues at multiple sites.

### Random example (Blocked image):
http://www.imagebam.com/image/4e084b119575075/

### Problem rule:
`.com/ad/`

### Additional info:
The whitelisting rule that I've had in my own filter, for a long time, is this one (which only fixes the issue with blocked images at two sites): 
`@@||.com/ad/*$image,~third-party,domain=imagebam.com|imgbox.com`
However, all major filter lists (**AdGuard**, **EasyList**, **uBO**) contains a large number of exceptions for this rule, which I recently mentioned here:
https://github.com/AdguardTeam/AdguardFilters/issues/57111#issuecomment-641919131

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by THEtomaso** [comment]
> https://github.com/wolfbeast/lunarblocklist/commit/c512bbf0a9984362ce919c59f7e536744784ebc9

You forgot to include an exception for the site that I posted an actual example for, in my first post (`imagebam.com`). :)

**Comment by wolfbeast** [comment]
FYI, Imagebam is absolutely terrible.

**Comment by THEtomaso** [comment]
> Imagebam is absolutely terrible.

Not using it myself.

BTW; your list isn't updating.
Perhaps it's because you didn't change the version number?

**Comment by wolfbeast** [comment]
> BTW; your list isn't updating.

I'm not pushing changes out daily. I have other things to do too.
